name: Release alpha version
description: Release alpha version
inputs:
  npm-token:
    description: Token to push code with
    required: true
runs:
  using: "composite"
  steps:
    - name: Configure git user
      run: |
        git config --local user.email "diegopf@users.noreply.github.com"
        git config --local user.name "diegopf"
      shell: bash
    - name: Create .npmrc file with authorization token
      run: echo //registry.npmjs.org/:_authToken=${NPM_TOKEN} > .npmrc
      shell: bash
      env:
        NPM_TOKEN: ${{ inputs.npm-token }}
    - name: Create report file
      run: date +%s > report.txt
      shell: bash
    # - name: Push changes to GitHub
    #   run: git push --follow-tags
    #   shell: bash
    - name: Commit report
      run: |
          git commit -am "Automated report"
          git push
      shell: bash      
