name: Log tag name on push
on: [push]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v2
        with:
          node-version: "18"
      - name: Log branch name
        run: echo "branch name is ${{ github.base_ref }}"
      - name: Log tag name
        if: startsWith(github.ref, 'refs/tags/release-') && github.base_ref == 'refs/heads/main'
        run: echo "release tag name is ${{ github.ref }} and the branch is ${{ github.ref_name }}"
