name: Log tag name on push
on: [push]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v2
        with:
          node-version: "18"
      - name: Log tag name
        if: startsWith(github.ref, 'refs/tags/release-')
        run: echo "release tag name is ${{ github.ref }}"
