name: Test
on: [push, pull_request]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "show github ref"
        run: echo "Github ref ${{ github.ref }}"
      # - name: "base_ref"
      #   run: echo "pr target is ${{ github.base_ref }}"
      # - name: "github.ref"
      #   run: echo "github ref ${{ github.ref }}"
      # - name: "github.event.head_commit.message"
      #   run: echo "github ref ${{ github.event.head_commit.message }}"
      - uses: actions/checkout@v3
      - name: Install lerna and all packages
        run: npm ci
      - name: Run tests in all packages
        run: npm run test
      - name: Test release action
        if: ${{ !startsWith(github.event.head_commit.message, 'v0') && github.ref_name == 'main'}}
        uses: ./.github/actions/release-alpha
        with:
          npm-token: ${{ secrets.TOKEN }}
      - name: Only run if commit message does not start with publish
        if: ${{ !startsWith(github.event.head_commit.message, 'v0.0.1') && github.actor == 'diegopf' }}
        run: echo "this is not a release commit"
