name: Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container: cypress/browsers:node14.17.0-chrome91-ff89
    steps:
      - name: 'pr merged'
        run: echo "pr was merged ${{ github.event.pull_request.merged }}"
      - name: 'base_ref'
        run: echo "pr target is ${{ github.base_ref }}"
      - name: 'github.ref'
        run: echo "github ref ${{ github.ref }}"
      # - uses: actions/checkout@v2
      # - name: Install lerna and all packages
      #   run: npm ci
      # - name: test action
      #   uses: ./.github/actions/show-user
      #   with:
      #     npm-token: ${{ secrets.GITHUB_TOKEN }}        
      # - name: Run tests in all packages
      #   run: npm run test
      - name: Only run if pr was merged
        if: github.event.pull_request.merged == true      
        run: echo "pr was merged ${{ github.event.pull_request.merged }}"